apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: beuthdritter/synthnet-transfer-learning
      env:
        - name: GIT_NAME
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: username
              optional: false
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-creds
              key: token
              optional: false
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-secret
              key: secret
              optional: false
      volumeMounts:
        - name: synthnet-finetuning-volume
          mountPath: /workspace/data
        - name: output-volume
          mountPath: /workspace/out
        - name: src-volume
          mountPath: /src-pv
        - mountPath: /dev/shm
          name: dshm
      command: ["/bin/bash", "-c"]
      args:
        # - while true; do sleep 30; done;
        - cd /src-pv/synthnet-transfer-learning;
          git checkout main;
          git pull;
          cd /workspace;
          cp -r /src-pv/synthnet-transfer-learning/* /workspace;
          python src/train.py -m 'experiment=STL-visda2017/vitb16_ft_adamw1e-1_calr.yaml, STL-visda2017/vitb16_ft_adamw1e-3_calr.yaml,STL-visda2017/vitb16_ft_adamw1e-5_calr.yaml' logger.wandb.project=lightning_toy_runs data.toy=true data.batch_size=32 trainer.max_epochs=5;
      resources:
        limits:
          nvidia.com/gpu: 1
  nodeSelector:
    gpu: v100
  volumes:
    - name: synthnet-finetuning-volume
      persistentVolumeClaim:
        claimName: synthnet-finetuning-pvc
    - name: output-volume
      persistentVolumeClaim:
        claimName: output-pvc
    - name: src-volume
      persistentVolumeClaim:
        claimName: src-pvc
    - name: dshm
      emptyDir:
        medium: Memory
